### ISSUE TITLE
trainx_embed=load_embeddings(trainx_pix) NameError: name 'trainx_pix' is not defined

### ISSUE THREAD

**Issue by larvaaaaa** [Nagasai524/Masked-Face-Recognition-using-MTCNN-and-FaceNet-End-to-End-Deploymnet-using-Stremlit-#1]
Hello, I'm new in github and I have interest with your repository. But  I have a problem when run embeddings_generator.py. The problem is

File "/content/Masked-Face-Recognition-using-Facenet/embeddings_generator.py", line 72, in <module>
    trainx_embed=load_embeddings(trainx_pix)
NameError: name 'trainx_pix' is not defined

I don't know how to fix it. Can you help me? and I'm sorry if asking here is wrong.

**Comment by Hes11q** [comment]
File "/content/Masked-Face-Recognition-using-Facenet/embeddings_generator.py", line 72, in
trainx_embed=load_embeddings(trainx_pix)
NameError: name 'trainx_pix' is not defined

hello can u help with this problem
